---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-write-deployment
  labels:
    app: mysql-write
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mysql-write
  template:
    metadata:
      labels:
        app: mysql-write
    spec:
      containers:
        - name: mysql-write
          image: mysql:5.7
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              subPath: "mysql"
              name: mysql-data
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets-adv
                  key: MYSQL_ROOT_PASSWORD

      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-disk
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-write-service
spec:
  selector:
    app: mysql-write
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
